openapi: 3.0.0
info:
  title: Your Internal API
  description: Internal API documentation
  version: 1.0.0
  contact:
    name: Your Team
    email: team@company.com

# Server configuration
servers:
  - url: http://localhost:4000
    description: Development server
  - url: https://api.yourcompany.com
    description: Production server

# Tags for grouping operations
tags:
  - name: User
    description: Operations about users
  - name: Payment
    description: Operations about payments and billing

# API Paths and Operations
paths:
  /users:
    post:
      tags:
        - User
      summary: Create a new user
      description: Creates a new user account with the provided details.
      operationId: createUser
      requestBody:
        description: User object that needs to be added to the store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid input provided
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{userId}:
    get:
      tags:
        - User
      summary: Get user by user ID
      description: Retrieve a single user's information by their unique ID.
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: string
            pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
            example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      tags:
        - User
      summary: Update an existing user
      description: Update an existing user's details by their unique ID. Password updates should be handled by a separate endpoint.
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: ID of user that needs to be updated
          required: true
          schema:
            type: string
            pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
            example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
      requestBody:
        description: User object with updated data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid input
        "404":
          description: User not found

    delete:
      tags:
        - User
      summary: Delete a user
      description: Deletes a user by their unique ID.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: The ID of the user that needs to be deleted
          required: true
          schema:
            type: string
            pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
            example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
      responses:
        "204":
          description: User deleted successfully (No Content)
        "404":
          description: User not found

  /api/payments/checkout-session:
    post:
      tags:
        - Payment
      summary: Create Stripe checkout session
      description: Creates a new Stripe checkout session for payment processing.
      operationId: createCheckoutSession
      requestBody:
        description: Checkout session details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckoutSessionRequest"
      responses:
        "201":
          description: Checkout session created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutSessionResponse"
        "400":
          description: Invalid input provided
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/payments/webhook:
    post:
      tags:
        - Payment
      summary: Handle Stripe webhook
      description: Handles incoming Stripe webhook events for payment processing.
      operationId: handleStripeWebhook
      requestBody:
        description: Stripe webhook payload
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Raw Stripe webhook payload
      responses:
        "200":
          description: Webhook processed successfully
        "400":
          description: Invalid webhook signature or payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/payments/verify/{sessionId}:
    get:
      tags:
        - Payment
      summary: Verify payment success
      description: Verifies if a payment session was completed successfully.
      operationId: verifyPaymentSuccess
      parameters:
        - name: sessionId
          in: path
          description: Stripe session ID to verify
          required: true
          schema:
            type: string
            example: "cs_test_1234567890"
      responses:
        "200":
          description: Payment verification result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentVerificationResponse"
        "404":
          description: Session not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/payments/history/{userId}:
    get:
      tags:
        - Payment
      summary: Get payment history
      description: Retrieves payment history for a specific user.
      operationId: getPaymentHistory
      parameters:
        - name: userId
          in: path
          description: ID of user to get payment history for
          required: true
          schema:
            type: string
            pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
            example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Number of records per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        "200":
          description: Payment history retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentHistoryResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/payments/plans:
    get:
      tags:
        - Payment
      summary: Get available plans
      description: Retrieves all available interview plans and pricing.
      operationId: getPlans
      responses:
        "200":
          description: Plans retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlansResponse"

# Reusable Components
components:
  schemas:
    # Schema for creating a user (includes passwords)
    UserCreate:
      type: object
      required:
        - name
        - email
        - password
        - passwordConfirmation
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        mobileNumber:
          type: string
          pattern: '^\+[1-9]\d{1,14}$'
          example: "+14155552671"
        password:
          type: string
          format: password
          description: User's password (at least 8 characters)
          example: "strongPassword123"
        passwordConfirmation:
          type: string
          format: password
          description: Confirmation of the user's password
          example: "strongPassword123"

    # Schema for updating a user (passwords are not updated here)
    UserUpdate:
      type: object
      properties:
        name:
          type: string
          example: "Johnathan Doe"
        email:
          type: string
          format: email
          example: "johnathan.doe@example.com"
        mobileNumber:
          type: string
          pattern: '^\+[1-9]\d{1,14}$'
          example: "+14155552672"

    # Schema for API responses (does NOT include sensitive info like passwords)
    User:
      type: object
      properties:
        id:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        mobileNumber:
          type: string
          example: "+14155552671"
        interviewCredits:
          type: integer
          example: 5
        profilePicture:
          type: string
          nullable: true
          example: "https://example.com/profile.jpg"
        isActive:
          type: boolean
          example: true
        emailVerified:
          type: boolean
          example: true
        mobileNumberVerified:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: "2024-07-29T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-07-29T10:30:00Z"

    # Payment related schemas
    CheckoutSessionRequest:
      type: object
      required:
        - planId
        - userId
      properties:
        planId:
          type: string
          enum: ["free_trial", "interview_bundle", "single_interview"]
          example: "interview_bundle"
        userId:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        successUrl:
          type: string
          format: uri
          example: "https://yourapp.com/success"
        cancelUrl:
          type: string
          format: uri
          example: "https://yourapp.com/cancel"

    CheckoutSessionResponse:
      type: object
      properties:
        sessionId:
          type: string
          example: "cs_test_1234567890"
        url:
          type: string
          format: uri
          example: "https://checkout.stripe.com/pay/cs_test_1234567890"

    Payment:
      type: object
      properties:
        id:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          example: "01BX5ZZKBKACT-8RNJEHP-S-T9"
        stripeSessionId:
          type: string
          nullable: true
          example: "cs_test_1234567890"
        stripePaymentIntentId:
          type: string
          nullable: true
          example: "pi_test_1234567890"
        amount:
          type: number
          format: decimal
          example: 249.00
        currency:
          type: string
          example: "INR"
        planType:
          type: string
          example: "interview_bundle"
        interviewCredits:
          type: integer
          example: 5
        status:
          type: string
          enum: ["pending", "completed", "failed", "cancelled"]
          example: "completed"
        paymentMethod:
          type: string
          nullable: true
          example: "card"
        receiptUrl:
          type: string
          nullable: true
          format: uri
          example: "https://pay.stripe.com/receipts/example"
        metadata:
          type: object
          nullable: true
          additionalProperties: true
        userId:
          type: string
          pattern: '^[0-9A-HJKMNP-TV-Z]{26}$'
          example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        createdAt:
          type: string
          format: date-time
          example: "2024-07-29T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-07-29T10:30:00Z"

    PaymentVerificationResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        session:
          type: object
          properties:
            id:
              type: string
              example: "cs_test_1234567890"
            status:
              type: string
              example: "complete"
            payment_status:
              type: string
              example: "paid"
        payment:
          $ref: "#/components/schemas/Payment"

    PaymentHistoryResponse:
      type: object
      properties:
        payments:
          type: array
          items:
            $ref: "#/components/schemas/Payment"
        pagination:
          type: object
          properties:
            page:
              type: integer
              example: 1
            limit:
              type: integer
              example: 10
            total:
              type: integer
              example: 25
            totalPages:
              type: integer
              example: 3

    Plan:
      type: object
      properties:
        id:
          type: string
          example: "interview_bundle"
        name:
          type: string
          example: "Power Pack"
        amount:
          type: integer
          example: 24900
        priceInCents:
          type: integer
          example: 24900
        credits:
          type: integer
          example: 5
        label:
          type: string
          example: "₹249 / 5 interviews"
        description:
          type: string
          example: "For the serious job seeker. Be prepared for every round."
        features:
          type: array
          items:
            type: string
          example:
            - "5 Interview Credits"
            - "Over 50% discount per interview"
            - "Credits never expire"
            - "Full access to all features"
        actionLabel:
          type: string
          example: "Buy Power Pack"
        popular:
          type: boolean
          example: true
        isFree:
          type: boolean
          example: false
        formattedPrice:
          type: string
          example: "₹249"
        currency:
          type: string
          example: "INR"
        symbol:
          type: string
          example: "₹"

    PlansResponse:
      type: object
      properties:
        plans:
          type: array
          items:
            $ref: "#/components/schemas/Plan"

    # Generic Error Schema
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 404
        message: "Resource not found"