import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import { User } from '../entity/user.entity';
import { AutoGeneratedMigration1749717225965 } from '../migrations/1749717225965-AutoGeneratedMigration';

dotenv.config();

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '3306'),
  username: process.env.DB_USERNAME || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_DATABASE || 'test_db',
  synchronize: false,
  logging: false,
  entities: [User],
  migrations: [AutoGeneratedMigration1749717225965],
});
