import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import { User } from '../entity/user.entity';
import { BlacklistedToken } from '../entity/blacklisted-token.entity';
import { InterviewPrompt } from '../entity/InterviewPrompt';

import { AutoGeneratedMigration1750088585756 } from '../migrations/1750088585756-AutoGeneratedMigration';
import { AutoGeneratedMigration1750143299041 } from '../migrations/1750143299041-AutoGeneratedMigration';
import { AutoGeneratedMigration1749711524252 } from '../migrations/1749711524252-AutoGeneratedMigration';

dotenv.config();

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '3306'),
  username: process.env.DB_USERNAME || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_DATABASE || 'test_db',
  synchronize: false,
  logging: false,
  entities: [User, BlacklistedToken, InterviewPrompt],
  migrations: [
    AutoGeneratedMigration1750088585756,
    AutoGeneratedMigration1750143299041,
    AutoGeneratedMigration1749711524252
  ],
});
