import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1749711524252 implements MigrationInterface {
    name = 'AutoGeneratedMigration1749711524252'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`interview_prompt\` (\`id\` char(26) NOT NULL, \`question\` varchar(256) NOT NULL, \`answer\` text NOT NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`interview_prompt\``);
    }

}
