import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1750662873432 implements MigrationInterface {
    name = 'AutoGeneratedMigration1750662873432'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`interview_session\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`interviewId\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'active', \`startedAt\` timestamp NULL, \`endedAt\` timestamp NULL, \`durationInSeconds\` int NOT NULL DEFAULT '0', \`creditsUsed\` int NOT NULL DEFAULT '0', \`sessionData\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`interview_session\``);
    }

}
