import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1750683922168 implements MigrationInterface {
    name = 'AutoGeneratedMigration1750683922168'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`interview_prompt\` ADD \`userId\` varchar(255) NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`interview_prompt\` DROP COLUMN \`userId\``);
    }

}
