import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1750232227645 implements MigrationInterface {
    name = 'AutoGeneratedMigration1750232227645'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_3a6f6a955e65852415ee7bbf1e\` ON \`user\``);
       
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_3a6f6a955e65852415ee7bbf1e\` ON \`user\` (\`mobileNumber\`)`);
    }

}
