import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1750241554669 implements MigrationInterface {
    name = 'AutoGeneratedMigration1750241554669'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`interview\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment\` (\`id\` varchar(36) NOT NULL, \`stripeSessionId\` varchar(255) NULL, \`stripePaymentIntentId\` varchar(255) NULL, \`amount\` decimal(10,2) NOT NULL, \`currency\` varchar(255) NOT NULL, \`planType\` varchar(255) NOT NULL, \`interviewCredits\` int NOT NULL, \`status\` varchar(255) NOT NULL DEFAULT 'completed', \`paymentMethod\` varchar(255) NULL, \`receiptUrl\` varchar(255) NULL, \`metadata\` json NULL, \`userId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`payment\``);
        await queryRunner.query(`DROP TABLE \`interview\``);
    }

}
