import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1750855984646 implements MigrationInterface {
    name = 'AutoGeneratedMigration1750855984646'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`interview_prompt\` ADD \`sessionId\` varchar(255) NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`interview_prompt\` DROP COLUMN \`sessionId\``);
    }

}
