import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1750143299041 implements MigrationInterface {
    name = 'AutoGeneratedMigration1750143299041'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`blacklisted_token\` (\`id\` varchar(255) NOT NULL, \`token\` varchar(255) NOT NULL, \`blacklistedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`blacklisted_token\``);
    }

}
