import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1751362141657 implements MigrationInterface {
    name = 'AutoGeneratedMigration1751362141657'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`resume\` (\`id\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`fileName\` varchar(255) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`fileSize\` int NOT NULL, \`mimeType\` varchar(255) NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`resume\``);
    }

}
