import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1751373992977 implements MigrationInterface {
    name = 'AutoGeneratedMigration1751373992977'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`support_ticket\` (\`id\` varchar(255) NOT NULL, \`subject\` varchar(200) NOT NULL, \`message\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`status\` enum ('open', 'in_progress', 'resolved') NOT NULL DEFAULT 'open', \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_506b4b9f579fb3adbaebe3950c\` (\`id\`), INDEX \`IDX_7df66b3c96ac736a25423c54e2\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_7df66b3c96ac736a25423c54e2\` ON \`support_ticket\``);
        await queryRunner.query(`DROP INDEX \`IDX_506b4b9f579fb3adbaebe3950c\` ON \`support_ticket\``);
        await queryRunner.query(`DROP TABLE \`support_ticket\``);
    }

}
