import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1751022214922 implements MigrationInterface {
    name = 'AutoGeneratedMigration1751022214922'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`resume\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`role\` varchar(255) NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`resume\``);
    }

}
