import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1751297117128 implements MigrationInterface {
    name = 'AutoGeneratedMigration1751297117128'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`support_ticket\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` ADD \`id\` varchar(255) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`CREATE INDEX \`IDX_506b4b9f579fb3adbaebe3950c\` ON \`support_ticket\` (\`id\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_506b4b9f579fb3adbaebe3950c\` ON \`support_ticket\``);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`support_ticket\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
    }

}
