import { AutoGeneratedMigration1749711524252 } from "./1749711524252-AutoGeneratedMigration";
import { AutoGeneratedMigration1750088585756 } from "./1750088585756-AutoGeneratedMigration";
import { AutoGeneratedMigration1750143299041 } from "./1750143299041-AutoGeneratedMigration";
import { AutoGeneratedMigration1750157259129 } from "./1750157259129-AutoGeneratedMigration";
import { AutoGeneratedMigration1750232227645 } from "./1750232227645-AutoGeneratedMigration";
import { AutoGeneratedMigration1750241554669 } from "./1750241554669-AutoGeneratedMigration";
import { AutoGeneratedMigration1750683922168 } from "./1750683922168-AutoGeneratedMigration";

export const migrations = [
  AutoGeneratedMigration1750088585756,
  AutoGeneratedMigration1750143299041,
  AutoGeneratedMigration1750157259129,
  AutoGeneratedMigration1749711524252,
  AutoGeneratedMigration1750232227645,
  AutoGeneratedMigration1750241554669,
  AutoGeneratedMigration1750683922168,
].sort((a, b) => a.name.localeCompare(b.name));
