import { AutoGeneratedMigration1749711524252 } from "./1749711524252-AutoGeneratedMigration";
import { AutoGeneratedMigration1750088585756 } from "./1750088585756-AutoGeneratedMigration";
import { AutoGeneratedMigration1750143299041 } from "./1750143299041-AutoGeneratedMigration";
import { AutoGeneratedMigration1750157259129 } from "./1750157259129-AutoGeneratedMigration";

export const migrations = [
  AutoGeneratedMigration1750088585756,
  AutoGeneratedMigration1750143299041,
  AutoGeneratedMigration1750157259129,
  AutoGeneratedMigration1749711524252
].sort((a, b) => a.name.localeCompare(b.name));
