import { AutoGeneratedMigration1750073010447 } from "./1750073010447-AutoGeneratedMigration";

export const migrations = [
  AutoGeneratedMigration1750073010447

].sort((a, b) => a.name.localeCompare(b.name));